version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend:latest # 确保设置了正确的镜像标签

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - /root/nginx.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - frontend
    ports:
      - "8081:80"
