# version: "3.8"

# services:
#   frontend:
#     image: node:23.3.0
#     container_name: frontend
#     working_dir: /app
#     volumes:
#       - .:/app
#     command: npm install && npm run build
#     ports:
#       - "3000:3000"
#     depends_on:
#       - nginx

#   nginx:
#     image: nginx:alpine
#     container_name: nginx
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./dist:/usr/share/nginx/html
#     ports:
#       - "8080:80"
#     depends_on:
#       - frontend

version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    # ports:
    #   - "8080:80"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - frontend
